###################
## Config        ##
###################

[config]
skip_core_tasks = true

[env]
OPENSSL_DIR="C:\\Program Files\\OpenSSL-Win64"

###################
## Test          ##
###################

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.test-watch]
command = "cargo"
args = ["watch", "-w", "../../shared/rust", "-w", ".", "-x", "test --features local-quiet -- --nocapture"]

###################
## Dev           ##
###################

[tasks.dev]
run_task = { name = [ "google-sql-proxy", "server-local-quiet", ], parallel = true }


[tasks.dev-warnings]
run_task = { name = [ "google-sql-proxy", "server-local", ], parallel = true }


[tasks.server-local]
command = "systemfd"
args = ["--no-pid", "-s", "http::8081", "--", "cargo", "watch", "-w", "../../shared/rust", "-w", ".", "-x", "run --features local"]

[tasks.server-local-quiet]
command = "systemfd"
args = ["--no-pid", "-s", "http::8081", "--", "cargo", "watch", "-w", "../../shared/rust", "-w", ".", "-x", "run --features local-quiet"]

[tasks.google-sql-proxy]
env = { CARGO_MAKE_SCRIPT_FORCE_PIPE_STDIN = true }
script = ["cd ../../build-utils","npm run cloud-sql-proxy"]
