name: Test, Build, and Deploy

on: [push]

env:
  GITHUB_SHA: ${{github.sha}}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Extract label 
        shell: bash
        run: echo "##[set-output name=label;]$(echo \"[${GITHUB_REF#refs/heads/} - ${{github.event.repository.name}} - build]\")"
        id: extract_label

      - name: Notify slack
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"CFYR62BRC\",\"text\":\"${{steps.extract_label.outputs.label}} starting...\"}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: checkout repo
        uses: actions/checkout@v1

      - name: run tests
        run: docker build --target tests .
        env:
          DOCKER_BUILDKIT: 1

      - name: Notify slack of all status
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"CFYR62BRC\",\"text\":\"${{steps.extract_label.outputs.label}} ${{job.status}}\"}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: always()

      - name: Notify slack if success and deploy will happen
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"CFYR62BRC\",\"text\":\"${{steps.extract_label.outputs.label}} preparing for deploy...\"}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: success() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/sandbox')

  deploy-production:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: tests 
    env:
      PROJECT: "ji-cloud" 
      SERVICE: "ji-cloud-api" 
      CONTAINER_IMAGE: "ji-cloud-api"
      REGION: "europe-west1" 
    steps:

      - name: Extract label 
        shell: bash
        run: echo "##[set-output name=label;]$(echo \"[${GITHUB_REF#refs/heads/} - ${{github.event.repository.name}} - deploy]\")"
        id: extract_label

      - name: Notify slack
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"CFYR62BRC\",\"text\":\"${{steps.extract_label.outputs.label}} starting...\"}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: checkout repo
        uses: actions/checkout@v1

      # - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      # WAITING ON https://github.com/GoogleCloudPlatform/github-actions/pull/15 to be merged!
      - uses: dakom/github-actions/setup-gcloud@patch-new-sdk-url
        with:
          version: '272.0.0'
          service_account_key: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_JSON_KEY }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: gcloud auth configure-docker
            
      # Build the Docker image
      - name: Build
        run: |        
          docker build --target release -t gcr.io/"$PROJECT"/"$CONTAINER_IMAGE":"$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .
        env:
          DOCKER_BUILDKIT: 1

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: docker push gcr.io/$PROJECT/$CONTAINER_IMAGE:$GITHUB_SHA

      # Deploy to cloud run
      - name: Deploy
        run: gcloud run deploy "$SERVICE" --project "$PROJECT" --region "$REGION" --image gcr.io/"$PROJECT"/"$CONTAINER_IMAGE":"$GITHUB_SHA" --platform managed

      - name: Notify slack of all status
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"CFYR62BRC\",\"text\":\"${{steps.extract_label.outputs.label}} ${{job.status}}\"}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: always()


  deploy-sandbox:
    if: github.ref == 'refs/heads/sandbox'
    runs-on: ubuntu-latest
    needs: tests 
    env:
      PROJECT: "ji-cloud-developer-sandbox"
      SERVICE: "ji-cloud-api-sandbox" 
      CONTAINER_IMAGE: "ji-cloud-api-sandbox"
      REGION: "europe-west1" 
    steps:
      - name: Extract label 
        shell: bash
        run: echo "##[set-output name=label;]$(echo \"[${GITHUB_REF#refs/heads/} - ${{github.event.repository.name}} - deploy]\")"
        id: extract_label

      - name: Notify slack
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"CFYR62BRC\",\"text\":\"${{steps.extract_label.outputs.label}} starting...\"}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: checkout repo
        uses: actions/checkout@v1

      # - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      # WAITING ON https://github.com/GoogleCloudPlatform/github-actions/pull/15 to be merged!
      - uses: dakom/github-actions/setup-gcloud@patch-new-sdk-url
        with:
          version: '272.0.0'
          service_account_key: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_JSON_KEY_SANDBOX }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: gcloud auth configure-docker
            
      # Build the Docker image
      - name: Build
        run: |        
          docker build --target sandbox -t gcr.io/"$PROJECT"/"$CONTAINER_IMAGE":"$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .
        env:
          DOCKER_BUILDKIT: 1

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: docker push gcr.io/$PROJECT/$CONTAINER_IMAGE:$GITHUB_SHA

      # Deploy to cloud run
      - name: Deploy
        run: gcloud run deploy "$SERVICE" --project "$PROJECT" --region "$REGION" --image gcr.io/"$PROJECT"/"$CONTAINER_IMAGE":"$GITHUB_SHA" --platform managed

      - name: Notify slack of all status
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"CFYR62BRC\",\"text\":\"${{steps.extract_label.outputs.label}} ${{job.status}}\"}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: always()