name: Module - App - Release

on:
  push:
    branches: [ master ]
    paths:
    - 'shared/**'
    - 'frontend/config/**'
    - 'frontend/apps/crates/components/**'
    - 'frontend/apps/crates/utils/**'
    - 'frontend/apps/crates/entry/module/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [poster, video, tapping-board, drag-drop, memory, matching, flashcards, card-quiz, cover, resource-cover, legacy, find-answer]
        mode: [edit, play]
    steps:

      - name: checkout repo
        uses: actions/checkout@v1

      - name: Extract label
        shell: bash
        run: echo "##[set-output name=label;]$(echo \"[${GITHUB_REF#refs/heads/} - module/${{ matrix.app }}/${{ matrix.mode }} - app]\")"
        id: extract_label

      - name: Notify slack
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"CFYR62BRC\",\"text\":\"${{steps.extract_label.outputs.label}} starting...\"}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: make nightly the default
        run: rustup default nightly

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: download cargo-make
        run: curl -u jewish-interactive:"$GITHUB_TOKEN" -s https://api.github.com/repos/sagiegurari/cargo-make/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | xargs -I {} wget -c https://github.com/sagiegurari/cargo-make/releases/latest/download/cargo-make-v{}-x86_64-unknown-linux-musl.zip -O cargo-make.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: extract cargo-make to folder
        run: unzip -j cargo-make.zip -d cargo-make

      - name: add cargo-make to path
        uses: dakom/actions-path@master
        with:
          path: ${{github.workspace}}/cargo-make

      - name: install npm deps
        run: npm ci
        working-directory: "./frontend/apps"

      - name: install npm deps (build-utils)
        run: npm ci
        working-directory: "./frontend/build-utils"

      - name: build
        run: cargo make release "module/${{ matrix.app }}/${{ matrix.mode }}"
        working-directory: "./frontend/apps"
        env:
          LOCAL_CDN_FRONTEND_DIR: ${{ github.workspace }}/frontend

      - name: install google cloud sdk
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: '295.0.0'
          service_account_key: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_JSON_KEY }}

      - name: deploy to google cloud
        run: gsutil -m rsync -d -r frontend/apps/dist/module/${{ matrix.app }}/${{ matrix.mode }}/js gs://ji-cloud-frontend-origin-eu-001/module/${{ matrix.app }}/${{ matrix.mode }}/js

      - name: Notify slack of all status
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"CFYR62BRC\",\"text\":\"${{steps.extract_label.outputs.label}} ${{job.status}}\"}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: always()
