name: Frontend - PR

on:
  pull_request:
    paths:
      - '.github/workflows/frontend.yml'
      - 'shared/**'
      - 'frontend/config/**'
      - 'frontend/apps/crates/components/**'
      - 'frontend/apps/crates/utils/**'
      - 'frontend/apps/crates/entry/admin/**'
      - 'frontend/apps/crates/entry/home/**'
      - 'frontend/apps/crates/entry/asset/**'
      - 'frontend/apps/crates/entry/user/**'
      - 'frontend/apps/crates/entry/community/**'
      - 'frontend/apps/crates/entry/kids/**'
      - 'frontend/apps/crates/entry/module/**'
      - 'frontend/ts-utils/**'
      - 'frontend/elements/**'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
#          toolchain: nightly
          toolchain: nightly-2023-06-08
          components: rustfmt

      - run: cargo check --all --manifest-path frontend/apps/Cargo.toml
      - run: cargo fmt --all --manifest-path frontend/apps/Cargo.toml --check
      - run: cargo check --all --manifest-path frontend/apps/Cargo.toml
